export const ResponseMessage = {
    DATABASE_CONNECTED: 'Database connected',
    PHONE_NO_ALREADY_EXIST: 'Phone number is already exist',
    USER_EMAIL_ALREADY_EXIST: 'Email id already exist',
    PHONE_NO_ALREADY_REGISTERED:
        'Phone number is already exist',
    USER_EMAIL_ALREADY_REGISTERED:
        'Email id already exist',
    SERVICE_DELETED: 'Service deleted successfully',
    USER_DISABLE: 'User has been deactivated',
    USER_REGISTERED: 'User registered successfully',
    SUBADMIN_DEACTIVE: 'Subadmin deactivated successfully',
    SUBADMIN_ACTIVE: 'Subadmin activated successfully',
    USER_UPDATED: 'User updated successfully',
    USER_CREATED: 'User created successfully',
    USER_DEACTIVE: 'User deactivated successfully',
    USER_ACTIVE: 'User activated successfully',
    USER_LOGOUT: 'User logged out successfully',
    USER_PROFILE_IMAGE_UPDATED: 'Profile image updated successfully',
    PROFILE_UPDATED: 'Profile updated successfully',
    INTERNAL_SERVER_ERROR: 'Internal server error',
    SENT_OTP: 'OTP has been sent to your email address',
    RESENT_OTP: 'OTP has been sent to your email address',
    INVALID_ID: 'Invalid id',
    SERVICE_EXIST: 'Service already exist',
    SERVICE_ADDED: 'Service added successfully',
    SERVICE_NOT_FOUND: 'Service not found',
    SERVICE_UPDATED: 'Service updated successfully',
    INVALID_PASSWORD: 'Invalid password',
    ADMIN_LOGGEDIN: 'Admin login successfully',
    USER_LOGGEDIN: 'User login successfully',
    BANNER_NOT_FOUND: 'Banner not found',
    BANNER_ALREADY_CREATED: 'Banner already exist',
    NOT_FOUND: 'User does not exist',
    BAD_REQUEST: 'Bad request',
    MOVIESLIDER_UPDATED: 'Banner updated successfully',
    BANNER_CREATED: 'Banner created successfully',
    BANNER_REMOVED: 'Banner removed successfully',
    ROLE_ADDED: 'Role add successfully',
    TOKEN_NOT_AUTHORIZED: 'Token not authorized',
    ROLE_ALREADY_CREATED: 'Role already exist',
    ROLE_UPDATED: 'Role updated successfully',
    ROLE_REMOVED: 'Role removed successfully',
    ALL_ROLE_FETCHED: 'All role fetched successfully',
    SUBADMIN_ALREADY_EXISTS: 'Sub admin already exist',
    ROLE_LIST_NOT_FOUND: 'Role list not found',
    ADMIN_NOT_FOUND: 'Admin not found',
    ROLE_PERMISSIONS_FETCHED: 'Role permissions fetched successfully',
    ADMIN_UPDATED: 'Admin updated successfully',
    BANNER_ACTIVE: 'Banner activated successfully',
    ADMIN_LOGOUT: 'Admin Logout successfully',
    YOUR_REQ_SENT: 'Your request sent successfully',
    EMAIL_MOBILE_EXIST_BOTH: 'Email and Mobile no is already exist',
    BOOKING_CANT_RESCHEDULE_LESS_THAN_2_HOURS:
        'Booking cant reschedule less than 2 hours',
    EMAIL_EXIST: 'Email id already exist',
    MOBILE_EXIST: 'Mobile no is already exist',
    EMAIL_NOT_FOUND: 'Email id does not exist',
    UPDATE_FAILED: 'Update failed',
    NOT_RIGHTS_TO_ADD_ADMIN: 'You have no rights to add admin',
    MOBILE_EMAIL_EXIST: 'Mobile number or email id already exist',
    SUBADMIN_UPDATED: 'Sub admin updated successfully',
    SUBADMIN_CREATED: 'Sub admin created successfully',
    SUBADMIN_REMOVED: 'Sub admin removed successfully',
    EXPERT_CREATED: 'Expert created successfully',
    EXPERT_UPDATED: 'Expert updated successfully',
    EXPERT_REMOVED: 'Expert removed successfully',
    EXPERT_NOT_FOUND: 'Expert not found',
    EXPERT_DEACTIVE: 'Expert deactivated successfully',
    EXPERT_ACTIVE: 'Expert activated successfully',
    EXPERT_ALREADY_EXISTS: 'Expert already exist',
    EXPERT_LOGGEDIN: 'Expert login successfully',
    ALL_EXPERT: 'All expert list',
    ALL_SUBADMINS: 'Get all subadmins successfully',
    ADMIN_DETAILS: 'Admin details',
    USER_FETCHED: 'Users fetched successfully',
    USER_NOT_FOUND: 'User not found',
    // USER_REMOVED: 'User removed successfully',
    USER_DELETED: 'User deleted successfully',
    USER_SINGLE_LIST: 'User list fetched successfully',
    USER_ALL_LIST: 'User list fetched successfully',
    EMAIL_REGISTERED_WITH_OTHER_SOCIAL_PLATFORM:
        'Email id already registered with other social platform',
    PRIVACY_POLICY_ADDED: 'Privacy policy created successfully',
    PRIVACY_POLICY_UPDATED: 'Privacy policy updated successfully',
    REFUND_POLICY_ADDED: 'Refund policy created successfully',
    REFUND_POLICY_UPDATED: 'Refund policy updated successfully',
    ABOUT_US_ADDED: 'About us details created successfully',
    ABOUT_US_UPDATED: 'About us details updated successfully',
    LEGAL_NOTICE_ADDED: 'Legal notice created successfully',
    LEGAL_NOTICE_UPDATED: 'Legal notice updated successfully',
    TERMS_AND_CONDITION_ADDED: 'Terms and conditions created successfully',
    TERMS_AND_CONDITION_UPDATED: 'Terms and conditions updated successfully',
    CMS_DETAILS_ADDED: 'Cms details added successfully',
    CMS_DETAILS_UPDATED: 'Cms details updated successfully',
    CMS_DETAILS_FETCHED: 'Cms details fetched successfully',
    CONTACTUS_LIST_NOT_FOUND: 'Contact us lead not found',
    CONTACTUS_LEAD_DETAILS_FETCHED:
        'Contact us lead details fetched successfully',
    FAQ_ADDED: 'FAQ added successfully',
    FAQ_UPDATED: 'FAQ updated successfully',
    FAQ_REMOVED: 'FAQ removed successfully',
    FAQ_LIST: 'FAQ list fetched successfully',
    TOKEN_NOT_VALID: 'Token not valid',
    SOMETHING_WENT_WRONG: 'Something went wrong',
    RESET_PASSWORD: 'Password reset successfully',
    PASSWORD_NOT_MATCH: 'Password not match',
    OLD_NEW_PASSWORD_ARE_MATCH: 'Old and new password are same',
    FIELDS_NOT_FOUND: 'Fields not found',
    OLDPASSWORD_DONT_MATCH: 'Old password dont match',
    PASSWORD_UPDATED_SUCCESSFULLY: 'Password updated successfully',
    VERIFICATION_COMPLETED: 'OTP has been verified successfully',
    INVALID_OTP: 'Invalid OTP',
    OTP_EXPIRED: 'OTP expired',
    CATEGORY_UPDATED: 'Category updated successfully',
    CATEGORY_ADDED: 'Category added successfully',
    CATEGORYNAME_EXIST: 'Category name already exist',
    SUB_CATEGORY_UPDATED: 'Sub category updated successfully',
    SUB_CATEGORY_ADDED: 'Sub category added successfully',
    SUB_CATEGORYNAME_EXIST: 'Sub category name already exist',
    SUB_CATEGORY_DETAILS: 'Sub category detail fetch successfully',
    SUB_CATEGORY_REMOVED: 'Sub category removed successfully',
    SUB_CATEGORY_BY_CATEGORY: 'Sub category fetched by category successfully',
    SUBCATEGORY_DEACTIVE: 'Sub category deactivated successfully',
    SUBCATEGORY_ACTIVE: 'Sub category activated successfully',
    SUBCATEGORY_NOT_FOUND: 'Sub category not found',
    ALL_SUB_CATEGORIES: 'All sub categories fetched successfully',
    ALL_BANNER: 'All banner fetched successfully',
    INVALID_CREDENTIALS: 'Invalid Credentials',
    ALL_CATEGORIES: 'All categories fetched',
    CATEGORY_REMOVED: 'Category removed successfully',
    EXPERT_DETAILS: 'Expert detail fetch successfully',
    EXPERT_EMAIL_ALREADY_EXIST: 'Email id already exist',
    CATEGORY_DETAILS: 'Category detail fetch successfully',
    BANNER_DEACTIVE: 'Banner deactivated successfully',
    PRODUCT_EXIST: 'Product already exist',
    PRODUCT_ADDED: 'Product added successfully',
    PRODUCT_REMOVED: 'Product removed successfully',
    DISCOUNT_AND_OFFER_ADDED: 'Discount and offer added successfully',
    DISCOUNT_AND_OFFER_UPDATED: 'Discount and offer updated successfully',
    DISCOUNT_AND_OFFER_LIST: 'Discount and offer list fetched successfully',
    DISCOUNT_AND_OFFER_STATUS_UPDATED:
        'Discount and offer status updated successfully',
    SERVICE_LIST: 'Service list fetched successfully',
    DISCOUNT_AND_OFFER_DETAILS:
        'Discount and offer details fetched successfully',
    DISCOUNT_AND_OFFER_DELETED: 'Discount and offer deleted successfully',
    DISCOUNT_AND_OFFER_NOT_FOUND: 'Discount and offer not found',
    PRODUCT_UPDATED: 'Product updated successfully',
    PRODUCT_LIST: 'Product list fetched successfully',
    PERMISSION_DENIED: 'Permission denied successfully',
    PRODUCT_NOT_FOUND: 'Product not found',
    PRODUCT_DELETED: 'Product deleted successfully',
    REMOVE_WISHLIST_PRODUCT: 'Product removed from wishlist successfully',
    PRODUCT_DETAILS: 'Product details fetched successfully',
    OTP_NOT_EXPIRED: 'OTP not expired',
    RATING_AND_REVIEW_CREATED: 'Rating and review created successfully',
    RATING_AND_REVIEW_UPDATED: 'Rating and review updated successfully',
    RATING_AND_REVIEW_REMOVED: 'Rating and review removed successfully',
    ALL_RATING_AND_REVIEW: 'All rating and review fetched successfully',
    RATING_AND_REVIEW_DETAILS: 'Rating and review details fetched successfully',
    RATING_AND_REVIEW_EXPERT:
        'Rating and review expert details fetched successfully',
    RATING_NOT_FOUND: 'Rating and review not found',
    RATING_DEACTIVE: 'Rating and review deactivated successfully',
    RATING_ACTIVE: 'Rating and review activated successfully',
    RATING_APPROVED: 'Rating and review approved successfully',
    RATING_REJECTED: 'Rating and review rejected successfully',
    ALREADY_RATING_AND_REVIEW_FOR_THIS_BOOKING:
        'You have already rated and reviewed for this booking.',
    OTP_SENT: 'OTP sent successfully',
    BOOKING_CREATED: 'Booking created successfully',
    BOOKING_DATE_NOT_AVAILABLE: 'Booking date not available',
    BOOKING_CANCELLED: 'Booking cancelled successfully',
    BOOKING_REMOVED: 'Booking removed successfully',
    BOOKING_APPROVED: 'Booking approved successfully',
    BOOKING_REJECTED: 'Booking rejected successfully',
    BOOKING_RESCHEDULE: 'Booking rescheduled successfully',
    BOOKING_CANT_RESCHEDULE:
        'Your booking will be cancelled So you can not reschedule',
    PRODUCT_LISTING_BY_USER_ID: 'Wishlist product fetched successfully',
    PRODUCT_ADDED_TO_WISHLIST: 'Product added to wishlist successfully',
    NOT_FOUND_PRODUCT_WISHLIST: 'Product not found in wishlist',
    PRODUCT_ALREADY_IN_WISHLIST: 'Product already in wishlist',
    ALL_BOOKINGS: 'All booking fetched successfully',
    EXPERT_BOOKINGS: 'Expert bookings fetched successfully',
    BOOKING_UPDATED: 'Booking updated successfully',
    BOOKING_FOUND: 'Booking fetched successfully',
    BOOKING_NOT_FOUND: 'Booking not found',
    PARTNER_APPLIED_SUCCESSFULLY: 'Partner applied successfully',
    PARTNER_NOT_FOUND: 'Partner not found',
    PARTNER_APPROVED: 'Partner approved successfully',
    PARTNER_REJECTED: 'Partner rejected successfully',
    All_PARTNER: 'All partner fetched successfully',
    PARTNER_DETAILS_FATCHED: 'Partner details fetched successfully',
    PAYMENT_SUCCESSFULLY: 'Payment verified successfully',
    PAYMENT_FAILED: 'Payment failed',
    SPECIALIZATION_LIST: 'Specialization list fetched successfully',
    SPECIALIZATION_UPDATED: 'Specialization updated successfully',
    SPECIALIZATION_ADDED: 'Specialization added successfully',
    SPECIALIZATION_REMOVED: 'Specialization removed successfully',
    SPECIALIZATION_FETCHED: 'Specialization fetched successfully',
    NO_BOOKINGS: 'No bookings found',
    TOTAL_EARNINGS: 'Total booking earnings fetched successfully',
    ALL_COUNTRY_FETCHED: 'All country fetched successfully',
    NO_COUNTRY_FOUND: 'No country found',
    ALL_CITY_FETCHED: 'All city fetched successfully',
    NO_CITY_FOUND: 'No city found',
    PRODUCTADDCART: 'Product added successfully',
    OUT_OF_STOCK: 'Product stock not available to given quantity',
    PRODUCT_REMOVED_FROM_CART: 'Product removed from cart successfully',
    CART_LIST: 'Get cart successfully',
    CART_NOT_FOUND: 'Cart not found',
    INVALID_REQUEST_DATA: 'You are not authorized to access',
    CART_DELETE: 'Cart removed successfully',
    UNAUTHORIZED_ACCESS: 'You can not able to delete cart',
    SETTINGS_UPDATED: 'Settings updated successfully',
    SETTINGS_FETCHED: 'Settings fetched successfully',
    PRODUCT_NOT_FOUND_IN_CART: 'Product not found in cart',
    TOGGLE_NOT: 'Status not updated',
    FAQ_DEACTIVATED: 'FAQ deactivated successfully',
    FAQ_ACTIVATED: 'FAQ activated successfully',
    PRODUCT_NOT_SELECTED: 'No products selected for the order',
    CART_EMPTY: 'No item in cart',
    INVALID_COUPON: 'invalid coupon code',
    ORDER_PLACED: 'Order place successfully',
    ORDER_CANCEL_DEADLINE_EXCEEDED:
        'You can only cancel orders within 24 hours of placing the order',
    SERVICE_PRODUCT_NOT_FOUND: 'Srevice product not found',
    INVALID_REQUEST: 'you can not add products',
    SERVICE_PRODUCT_NOT_FOUND_IN_CART: 'Service product ot found in cart',
    COUPON_NOT_APPLICABLE: 'Couponcode is not valid for this item',
    COUPON_VALID: 'Coupon apply successfully',
    EXPIRE_COUPON: 'CouponCode is expire',
    COUPON_REACH_MAX_LIMIT: 'CouponCode reach thair max limit',
    ORDER_LIST: 'Get orderlist successfully',
    ORDER_NOT_FOUND: 'Order not found',
    ORDER_ALREADY_CANCELLED: 'Order already cancelled',
    ORDER_CANCELLED: 'Order cancelled successfully',
    ORDER_RETURNED: 'Order return request submitted successfully',
    OFFER_ACTIVE: 'Discount and offer active successfully',
    OFFER_DEACTIVE: 'Discount and offer deactive successfully',
    BOOKING_RESCHEDULED: 'Booking rescheduled successfully',
    BOOKING_RESCHEDULEDUP: 'Booking rescheduled updated successfully',
    REBOOKING_NOT_FOUND: 'Rescheduled booking not found',
    REBOOKING_STATUS_UPDATED:
        'Rescheduled booking request approved successfully',
    REBOOKING_REJECTED: 'Rescheduled booking request rejected successfully',
    REBOOKING_DELETED: 'Rescheduled booking request deleted successfully',
    SINGLE_TRANSACTION_HISTORY_FETCHED:
        'Single transaction history fetched successfully',
    TRANSACTION_HISTORY_FETCHED: 'Transaction history fetched successfully',
    BOOKING_NOT_RESEDUAL_NOW:
        'Reschedule can only be done on or before 2 hours of the booking time',
        BOOKING_NOT_CANCEL:'Booking can only be done on or before 4 hours of the booking time',
    NOT_ALLOWED_RESEDUAL_NOW:
        'You have reached the maximum number of reschedule booking',
    COUPON_CODE_ALREADY: 'Coupon code already exist',
    INVALID_PRODUCT_OR_SERVICE_ID: 'Sorry, item is currently unavailable',
    INSUFFICIENT_SERVICE_PRODUCT_QUANTITY:
        'Item is not available your required quantity',
    IMAGE_SENT: 'File sent successfully',
    QUOTATION_REJECTED: 'Quotation rejected successfully',
    REFUND_FOUND: 'Refund found successfully',
    BOOKING_CHAT_CREATED: 'Booking chat created successfully',
    BOOKING_CHAT_ALREADY_EXIST: 'Booking chat already exist',
    ORDER_STATUS_UPDATE: 'Order status update successfully',
    ORDER_RETURNED_REQUESTED: 'Order return request submitted successfully',
    ORDER_RETURN_REQUEST_UPDATE: 'Order return request updated successfully',
    RETURN_PERIOD_EXPIRE: 'Return period has expired',
    RETURN_REQUEST_NOT_FOUND: 'Return order not found',
    RETURN_NOT_ACCEPT_NOT_ASSIGN_EXPERT:
        'Expert review already completed',
        RETURN_REQUEST_NOT_ACCEPTED:"First need to accept return request",
    RETURN_ORDER_REASSIGNED: 'Return order reassigned to a new expert',
    RETURN_REQUEST_ALL: 'Return order list successfully',
    ORDER_REVIEW_COMPLATE: 'Retrun order review done successfully',
    EXPERT_ORDER_REVIEW_NOT_FOUND: 'Expert order return review not found',
    ORDER_RETURN_REQUEST_NOT_APPROVED: 'Order return request rejected',
    ALREADY_REQUESTED_RETURNED: 'Order return request already in process',
    ORDER_RETURN_REQUEST_APPROVED: 'Order return request has been approved',
    ORDER_DETAIL_NOT_FOUND: 'Order not found',
    QUOTATION_NOT_FOUND: 'Quotation not found',
    REFUND_DELETED: 'Refund deleted successfully',
    QUOTATION_FETCHED: 'Quotation fetched successfully',
    REORDER_CREATED:'Re-order created successfully',
    REFUND_ALREADY_INITIATED:'Refund for this order has already been initiated'
}
